-- ============================================================
-- 009_seed_eo_chapters.sql
-- Seed eo_chapters table with the canonical 226-chapter list
-- (scraped from member.eonetwork.org/about/chapter-locations,
--  normalized via scripts/normalize-eo-chapters.mjs).
-- + Best-effort backfill of existing profiles.eo_chapter free-text values.
-- ============================================================

insert into public.eo_chapters (name, region, country, city, virtual) values
  ('EO Adelaide', 'Asia Pacific', 'Australia', 'Adelaide', false),
  ('EO Albany', 'United States - East', 'United States', 'Albany', false),
  ('EO Andhra Pradesh', 'South Asia', 'India', 'Vishakapatnam', false),
  ('EO APAC Bridge', 'Asia Pacific', 'Singapore', 'Singapore', true),
  ('EO Argentina', 'Latin America/Caribbean', 'Argentina', null, false),
  ('EO Arizona', 'United States - West', 'United States', 'Phoenix', false),
  ('EO Atlanta', 'United States - East', 'United States', 'Atlanta', false),
  ('EO Atlantic Canada', 'Canada', 'Canada', 'Halifax', false),
  ('EO Austin', 'United States - Central', 'United States', 'Austin', false),
  ('EO Austria', 'Europe', 'Austria', null, false),
  ('EO Bahrain', 'MEPA', 'Bahrain', null, false),
  ('EO Baltimore', 'United States - East', 'United States', 'Baltimore', false),
  ('EO Bangalore', 'South Asia', 'India', 'Bangalore', false),
  ('EO Bangkok Metropolitan', 'Asia Pacific', 'Thailand', 'Bangkok', false),
  ('EO Bangladesh', 'South Asia', 'Bangladesh', 'Dhaka', false),
  ('EO Barcelona', 'Europe', 'Spain', 'Barcelona', false),
  ('EO Beijing', 'North Asia', 'China', 'Beijing', false),
  ('EO Beijing Metropolitan', 'North Asia', 'China', 'Beijing', false),
  ('EO Belgium', 'Europe', 'Belgium', null, false),
  ('EO Berlin', 'Europe', 'Germany', 'Berlin', false),
  ('EO Beyond Japan Bridge', 'Japan', 'Japan', 'Tokyo', true),
  ('EO Bhopal', 'South Asia', 'India', 'Bhopal', false),
  ('EO Birmingham', 'United States - East', 'United States', 'Birmingham', false),
  ('EO Bogota', 'Latin America/Caribbean', 'Colombia', 'Bogota', false),
  ('EO Boston', 'United States - East', 'United States', 'Boston', false),
  ('EO Bulgaria', 'Europe', 'Bulgaria', 'Sofia', false),
  ('EO Cairo', 'MEPA', 'Egypt', 'Cairo', false),
  ('EO Calgary', 'Canada', 'Canada', 'Calgary', false),
  ('EO Canada Bridge', 'Canada', 'Canada', 'Edmonton', true),
  ('EO Cancun-Riviera Maya', 'Latin America/Caribbean', 'Mexico', null, false),
  ('EO Cape Town', 'MEPA', 'South Africa', 'Cape Town', false),
  ('EO Charleston', 'United States - East', 'United States', 'Charleston', false),
  ('EO Charlotte', 'United States - East', 'United States', 'Charlotte', false),
  ('EO Chennai', 'South Asia', 'India', 'Chennai', false),
  ('EO Chicago', 'United States - Central', 'United States', 'Chicago', false),
  ('EO China East', 'North Asia', 'China', 'Shanghai', false),
  ('EO Cincinnati', 'United States - Central', 'United States', 'Cincinnati', false),
  ('EO Cleveland', 'United States - Central', 'United States', 'Cleveland', false),
  ('EO Coimbatore', 'South Asia', 'India', 'Coimbatore', false),
  ('EO Colorado', 'United States - West', 'United States', 'Denver', false),
  ('EO Columbus', 'United States - Central', 'United States', 'Columbus', false),
  ('EO Connecticut', 'United States - East', 'United States', null, false),
  ('EO Costa Rica', 'Latin America/Caribbean', 'Costa Rica', 'San Jose', false),
  ('EO Curitiba', 'Latin America/Caribbean', 'Brazil', null, false),
  ('EO Dalian', 'North Asia', 'China', 'Dalian', false),
  ('EO Dallas', 'United States - Central', 'United States', 'Dallas', false),
  ('EO DC', 'United States - East', 'United States', 'Washington DC', false),
  ('EO Detroit', 'United States - Central', 'United States', 'Detroit', false),
  ('EO Dominican Republic', 'Latin America/Caribbean', 'Dominican Republic', 'Santo Domingo', false),
  ('EO Dubai', 'MEPA', 'United Arab Emirates', 'Dubai', false),
  ('EO Durban', 'MEPA', 'South Africa', 'Durban', false),
  ('EO Edmonton', 'Canada', 'Canada', 'Edmonton', false),
  ('EO El Salvador', 'Latin America/Caribbean', 'El Salvador', null, false),
  ('EO Europe Bridge', 'Europe', 'Netherlands', 'Amsterdam', true),
  ('EO Fort Worth', 'United States - Central', 'United States', 'Fort Worth', false),
  ('EO Germany - Rhine Ruhr', 'Europe', 'Germany', null, false),
  ('EO Germany - Southwest', 'Europe', 'Germany', null, false),
  ('EO Global', 'United States - Central', 'United States', 'Las Vegas', false),
  ('EO Goa', 'South Asia', 'India', null, false),
  ('EO Greater Bay Area Metropolitan', 'North Asia', 'China', 'Hong Kong', false),
  ('EO Greater China Bridge', 'North Asia', 'China', 'Shanghai', true),
  ('EO Greece', 'Europe', 'Greece', null, false),
  ('EO Guadalajara', 'Latin America/Caribbean', 'Mexico', 'Guadalajara', false),
  ('EO Guangzhou', 'North Asia', 'China', 'Guangzhou', false),
  ('EO Guatemala', 'Latin America/Caribbean', 'Guatemala', 'Guatemala City', false),
  ('EO Guayaquil', 'Latin America/Caribbean', 'Ecuador', null, false),
  ('EO Gujarat', 'South Asia', 'India', 'Ahmedabad', false),
  ('EO Gurgaon', 'South Asia', 'India', 'Gurgaon', false),
  ('EO Hamburg', 'Europe', 'Germany', 'Hamburg', false),
  ('EO Hawaii', 'United States - West', 'United States', 'Honolulu', false),
  ('EO Hokkaido', 'Japan', 'Japan', 'Sapporo', false),
  ('EO Hokuriku', 'Japan', 'Japan', 'Niigata', false),
  ('EO Hong Kong', 'North Asia', 'Hong Kong', 'Hong Kong', false),
  ('EO Houston', 'United States - Central', 'United States', 'Houston', false),
  ('EO Hyderabad', 'South Asia', 'India', 'Hyderabad', false),
  ('EO Ibaraki', 'Japan', 'Japan', null, false),
  ('EO Idaho', 'United States - West', 'United States', 'Boise', false),
  ('EO Indonesia', 'Asia Pacific', 'Indonesia', 'Jakarta', false),
  ('EO Indonesia East', 'Asia Pacific', 'Indonesia', null, false),
  ('EO Indore', 'South Asia', 'India', 'Indore', false),
  ('EO Inland Empire', 'United States - West', 'United States', 'Riverside', false),
  ('EO Iowa', 'United States - Central', 'United States', 'Des Moines', false),
  ('EO Ireland', 'Europe', 'Ireland', 'Dublin', false),
  ('EO Islamabad', 'MEPA', 'Pakistan', null, false),
  ('EO Israel', 'Europe', 'Israel', 'Tel Aviv', false),
  ('EO Italy', 'Europe', 'Italy', 'Milan', false),
  ('EO Jaipur', 'South Asia', 'India', 'Jaipur', false),
  ('EO Japan Korea Bridge', 'Japan', 'Japan', null, true),
  ('EO Jeddah', 'MEPA', 'Saudi Arabia', 'Jeddah', false),
  ('EO Johannesburg', 'MEPA', 'South Africa', 'Johannesburg', false),
  ('EO Jordan', 'MEPA', 'Jordan', 'Amman', false),
  ('EO Kanagawa', 'Japan', 'Japan', null, false),
  ('EO Kansai Metropolitan', 'North Asia', 'Japan', null, false),
  ('EO Kansas City', 'United States - Central', 'United States', 'Kansas City', false),
  ('EO Karachi', 'MEPA', 'Pakistan', 'Karachi', false),
  ('EO Kelowna', 'Canada', 'Canada', null, false),
  ('EO Kenya', 'MEPA', 'Kenya', null, false),
  ('EO Kerala', 'South Asia', 'India', 'Kochi', false),
  ('EO Kobe', 'Japan', 'Japan', 'Kobe', false),
  ('EO Kolkata', 'South Asia', 'India', 'Kolkata', false),
  ('EO Korea', 'North Asia', 'South Korea', 'Seoul', false),
  ('EO Kuwait', 'MEPA', 'Kuwait', 'Kuwait City', false),
  ('EO Kyoto', 'Japan', 'Japan', 'Kyoto', false),
  ('EO Kyushu', 'Japan', 'Japan', null, false),
  ('EO LAC Bridge', 'Latin America/Caribbean', null, null, true),
  ('EO Lahore', 'MEPA', 'Pakistan', 'Lahore', false),
  ('EO Las Vegas', 'United States - West', 'United States', 'Las Vegas', false),
  ('EO Lebanon', 'MEPA', 'Lebanon', null, false),
  ('EO Los Angeles', 'United States - West', 'United States', 'Los Angeles', false),
  ('EO Los Angeles - Valley', 'United States - West', 'United States', 'Woodland Hills', false),
  ('EO Louisiana', 'United States - Central', 'United States', 'New Orleans', false),
  ('EO Madrid', 'Europe', 'Spain', 'Madrid', false),
  ('EO Malaysia', 'Asia Pacific', 'Malaysia', 'Kuala Lumpur', false),
  ('EO Melbourne', 'Asia Pacific', 'Australia', 'Melbourne', false),
  ('EO MEPA Bridge', 'MEPA', null, null, true),
  ('EO Merida', 'Latin America/Caribbean', 'Mexico', 'Merida', false),
  ('EO Mexico City', 'Latin America/Caribbean', 'Mexico', 'Mexico City', false),
  ('EO Minnesota', 'United States - Central', 'United States', 'Minneapolis', false),
  ('EO Monterrey', 'Latin America/Caribbean', 'Mexico', 'Monterrey', false),
  ('EO Montreal', 'Canada', 'Canada', 'Montreal', false),
  ('EO Mumbai', 'South Asia', 'India', 'Mumbai', false),
  ('EO Munich', 'Europe', 'Germany', 'Munich', false),
  ('EO Nagoya', 'Japan', 'Japan', null, false),
  ('EO Nagpur', 'South Asia', 'India', 'Nagpur', false),
  ('EO Nashville', 'United States - East', 'United States', 'Nashville', false),
  ('EO Navi Mumbai', 'South Asia', 'India', 'Navi Mumbai', false),
  ('EO Nebraska', 'United States - Central', 'United States', 'Omaha', false),
  ('EO Nepal', 'South Asia', 'Nepal', 'Kathmandu', false),
  ('EO Netherlands', 'Europe', 'Netherlands', 'Amsterdam', false),
  ('EO New Delhi', 'South Asia', 'India', 'Delhi', false),
  ('EO New Jersey', 'United States - East', 'United States', 'Orange', false),
  ('EO New York', 'United States - East', 'United States', 'New York', false),
  ('EO New Zealand', 'Asia Pacific', 'New Zealand', null, false),
  ('EO Nicaragua', 'Latin America/Caribbean', 'Nicaragua', 'Managua', false),
  ('EO Noida', 'South Asia', 'India', 'Noida', false),
  ('EO North Japan', 'Japan', 'Japan', 'Sendai', false),
  ('EO North Karnataka', 'South Asia', 'India', 'Belgaum', false),
  ('EO Northeast India', 'South Asia', 'India', 'Guwahati', false),
  ('EO NY Long Island', 'United States - East', 'United States', 'Northport', false),
  ('EO Odisha', 'South Asia', 'India', 'Bhubaneswar', false),
  ('EO Okinawa', 'Japan', 'Japan', null, false),
  ('EO Oklahoma City', 'United States - Central', 'United States', 'Oklahoma City', false),
  ('EO Oman', 'MEPA', 'Oman', 'Muscat', false),
  ('EO Orange County', 'United States - West', 'United States', 'Orange County', false),
  ('EO Osaka', 'Japan', 'Japan', 'Osaka', false),
  ('EO Ottawa', 'Canada', 'Canada', 'Ottawa', false),
  ('EO Pacific Diamond Bridge', 'Asia Pacific', null, null, true),
  ('EO Panama', 'Latin America/Caribbean', 'Panama', 'Panama City', false),
  ('EO Paris', 'Europe', 'France', 'Paris', false),
  ('EO Perth', 'Asia Pacific', 'Australia', 'Perth', false),
  ('EO Philadelphia', 'United States - East', 'United States', 'Philadelphia', false),
  ('EO Philippines', 'Asia Pacific', 'Philippines', 'Metro Manila', false),
  ('EO Philippines South', 'Asia Pacific', 'Philippines', 'Cebu', false),
  ('EO Pittsburgh', 'United States - Central', 'United States', 'Pittsburgh', false),
  ('EO Poland', 'Europe', 'Poland', 'Warsaw', false),
  ('EO Portland', 'United States - West', 'United States', 'Portland', false),
  ('EO Porto Alegre', 'Latin America/Caribbean', 'Brazil', 'Porto Alegre', false),
  ('EO Portugal', 'Europe', 'Portugal', null, false),
  ('EO Puerto Rico', 'Latin America/Caribbean', 'United States', 'San Juan', false),
  ('EO Pune', 'South Asia', 'India', 'Pune', false),
  ('EO Punjab', 'South Asia', 'India', null, false),
  ('EO Quebec', 'Canada', 'Canada', 'Quebec City', false),
  ('EO Queensland', 'Asia Pacific', 'Australia', 'Brisbane', false),
  ('EO Queretaro-San Miguel', 'Latin America/Caribbean', 'Mexico', 'Queretaro', false),
  ('EO Quito', 'Latin America/Caribbean', 'Ecuador', 'Quito', false),
  ('EO Raipur', 'South Asia', 'India', 'Raipur', false),
  ('EO Raleigh Durham', 'United States - East', 'United States', 'Raleigh', false),
  ('EO Ranchi', 'South Asia', 'India', 'Ranchi', false),
  ('EO Reno Tahoe', 'United States - West', 'United States', 'Reno', false),
  ('EO Richmond', 'United States - East', 'United States', 'Richmond', false),
  ('EO Rio De Janeiro', 'Latin America/Caribbean', 'Brazil', 'Rio de Janeiro', false),
  ('EO Riyadh', 'MEPA', 'Saudi Arabia', 'Riyadh', false),
  ('EO Russia', 'Europe', 'Russia', 'Moscow', false),
  ('EO Sacramento', 'United States - West', 'United States', 'Sacramento', false),
  ('EO San Antonio', 'United States - Central', 'United States', 'San Antonio', false),
  ('EO San Diego', 'United States - West', 'United States', 'San Diego', false),
  ('EO San Francisco', 'United States - West', 'United States', 'San Francisco', false),
  ('EO Sao Paulo', 'Latin America/Caribbean', 'Brazil', 'São Paulo', false),
  ('EO Saskatoon', 'Canada', 'Canada', 'Saskatoon', false),
  ('EO Saudi East', 'MEPA', 'Saudi Arabia', null, false),
  ('EO Seattle', 'United States - West', 'United States', 'Seattle', false),
  ('EO Setouchi', 'Japan', 'Japan', null, false),
  ('EO Shanghai', 'North Asia', 'China', 'Shanghai', false),
  ('EO Shenyang', 'North Asia', 'China', 'Shenyang', false),
  ('EO Shenzhen', 'North Asia', 'China', 'Shenzhen', false),
  ('EO Silicon Valley', 'United States - West', 'United States', 'Silicon Valley', false),
  ('EO Singapore', 'Asia Pacific', 'Singapore', 'Singapore', false),
  ('EO South Asia Bridge', 'South Asia', 'India', 'New Delhi', true),
  ('EO South Asia Founders Bridge', 'South Asia', null, null, true),
  ('EO South Asia Platinum Bridge', 'South Asia', 'India', 'Kolkata', true),
  ('EO South Florida', 'United States - East', 'United States', 'Miami', false),
  ('EO Southeast Virginia', 'United States - East', 'United States', 'Hampton Roads', false),
  ('EO Southwest Ontario', 'Canada', 'Canada', null, false),
  ('EO Sri Lanka', 'South Asia', 'Sri Lanka', 'Colombo', false),
  ('EO St. Louis', 'United States - Central', 'United States', 'St. Louis', false),
  ('EO Suisse Romande', 'Europe', 'Switzerland', null, false),
  ('EO Surat', 'South Asia', 'India', 'Surat', false),
  ('EO Sydney', 'Asia Pacific', 'Australia', 'Sydney', false),
  ('EO Taipei', 'North Asia', 'Taiwan', 'Taipei', false),
  ('EO Tampa Bay', 'United States - East', 'United States', 'Tampa', false),
  ('EO Tanzania', 'MEPA', 'Tanzania', 'Dar es Salaam', false),
  ('EO Thailand', 'Asia Pacific', 'Thailand', 'Bangkok', false),
  ('EO Tokyo Central', 'Japan', 'Japan', 'Tokyo', false),
  ('EO Tokyo East', 'Japan', 'Japan', 'Tokyo', false),
  ('EO Tokyo Metropolitan', 'North Asia', 'Japan', 'Tokyo', false),
  ('EO Tokyo Platinum', 'Japan', 'Japan', null, false),
  ('EO Tokyo West', 'Japan', 'Japan', null, false),
  ('EO Toronto', 'Canada', 'Canada', 'Toronto', false),
  ('EO Tulsa', 'United States - Central', 'United States', 'Tulsa', false),
  ('EO Turkey', 'Europe', 'Turkey', null, false),
  ('EO Uganda', 'MEPA', 'Uganda', 'Kampala', false),
  ('EO UK-London', 'Europe', 'United Kingdom', 'London', false),
  ('EO US Central Bridge', 'United States - Central', 'United States', null, true),
  ('EO US East Bridge', 'United States - East', 'United States', null, true),
  ('EO Utah', 'United States - West', 'United States', 'Salt Lake City', false),
  ('EO Uttar Pradesh', 'South Asia', 'India', 'Lucknow', false),
  ('EO Uttarakhand', 'South Asia', 'India', 'Dehradun', false),
  ('EO Vadodara', 'South Asia', 'India', 'Vadodara', false),
  ('EO Vancouver', 'Canada', 'Canada', 'Vancouver', false),
  ('EO Vancouver Island', 'Canada', 'Canada', null, false),
  ('EO Vietnam', 'Asia Pacific', 'Vietnam', null, false),
  ('EO West Michigan', 'United States - Central', 'United States', 'Grand Rapids', false),
  ('EO Western New York', 'United States - East', 'United States', 'Rochester', false),
  ('EO Winnipeg', 'Canada', 'Canada', 'Winnipeg', false),
  ('EO Wisconsin', 'United States - Central', 'United States', 'Milwaukee', false),
  ('EO Zurich', 'Europe', 'Switzerland', 'Zurich', false)
on conflict (name) do update set
  region  = excluded.region,
  country = excluded.country,
  city    = excluded.city,
  virtual = excluded.virtual;

-- Best-effort backfill: try to match free-text profiles.eo_chapter to a known chapter.
-- Lowercase + strip 'eo ' prefix on both sides for fuzzy match.
update public.profiles p
set
  region          = ec.region,
  chapter_country = ec.country,
  chapter_city    = ec.city
from public.eo_chapters ec
where p.eo_chapter is not null
  and p.region is null
  and (
    lower(trim(p.eo_chapter)) = lower(ec.name)
    or lower(regexp_replace(trim(p.eo_chapter), '^eo\s+', '', 'i')) = lower(regexp_replace(ec.name, '^eo\s+', '', 'i'))
  );

